### ISSUE TITLE
Detect when transferred from server

### ISSUE THREAD

**Issue by itfoldy** [TerminalMC/AutoReconnect#2]
### Request Description

Add a feature where the auto command can be ran, if the server restarts and player goes to the hub (instead of disconnecting), since usually servers do that, instead of actually disconnecting you

This way we could run an auto command in the hub until the player gets back in the server he wants

I'm not talking about the new transfer packet, literally just bungeecord servers, etc

**Comment by NotRyken** [comment]
I have looked into that before, the short answer is that different servers do it in different ways, and there doesn't seem to be any event that's reliable enough to depend on.

If there's a chat message associated with disconnecting you could potentially achieve the desired result using ChatNotify

**Comment by itfoldy** [comment]
Is it possible to make ChatNotify type something aswell? I thought it was just visual/audio cues

**Comment by NotRyken** [comment]
There's an automatic-response feature available via advanced options

**Comment by itfoldy** [comment]
In that case, that would resolve this issue, but I think you should add this exact same feature into this mod, detect message in chat, and run auto command until success. (Since ChatNotify will probably run it only once)

**Comment by NotRyken** [comment]
That could be worthwhile yeah, though defining 'success' might be interesting

**Comment by NotRyken** [comment]
Closing this as I haven't come up with a good and reasonably simple way to implement it.
